<?xml version="1.0" encoding="utf-8"?><Database Name="QUAN_LY_VAN_BAN" Class="QLVBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-96CRGKS\SQLEXPRESS;Initial Catalog=QUAN_LY_VAN_BAN;User ID=sa" SettingsObjectName="DATA_LAYER.Properties.Settings" SettingsPropertyName="QUAN_LY_VAN_BANConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FILE_NAME" Member="FILE_NAMEs">
    <Type Name="FILE_NAME">
      <Column Name="ID_FILE" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_TAI_LIEU" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_VAN_BAN_DEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ID_VAN_BAN_DI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MO_RONG_FILE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEN_FILE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_VAN_BAN_NOI_BO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="VAN_BAN_DEN_FILE_NAME" Member="VAN_BAN_DEN" ThisKey="ID_VAN_BAN_DEN" OtherKey="ID_VAN_BAN_DEN" Type="VAN_BAN_DEN" IsForeignKey="true" />
      <Association Name="VAN_BAN_DI_FILE_NAME" Member="VAN_BAN_DI" ThisKey="ID_VAN_BAN_DI" OtherKey="ID_VAN_BAN" Type="VAN_BAN_DI" IsForeignKey="true" />
      <Association Name="VAN_BAN_NOI_BO_FILE_NAME" Member="VAN_BAN_NOI_BO" ThisKey="ID_VAN_BAN_NOI_BO" OtherKey="ID_VAN_BAN_NOI_BO" Type="VAN_BAN_NOI_BO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GROUPMENUFUNC" Member="GROUPMENUFUNCs">
    <Type Name="GROUPMENUFUNC">
      <Column Name="MENUFORMID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_NHAN_VIEN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ACCESS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MENUFORM_GROUPMENUFUNC" Member="MENUFORM" ThisKey="MENUFORMID" OtherKey="MENUFORMID" Type="MENUFORM" IsForeignKey="true" />
      <Association Name="SALE_NHAN_VIEN_GROUPMENUFUNC" Member="SALE_NHAN_VIEN" ThisKey="ID_NHAN_VIEN" OtherKey="ID_NHAN_VIEN" Type="SALE_NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_VAN_BAN" Member="LOAI_VAN_BANs">
    <Type Name="LOAI_VAN_BAN">
      <Column Name="ID_LOAI_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_LOAI_VAN_BAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEN_LOAI_VAN_BAN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MO_TA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="LOAI_VAN_BAN_VAN_BAN_DEN" Member="VAN_BAN_DENs" ThisKey="ID_LOAI_VAN_BAN" OtherKey="ID_LOAI_VAN_BAN" Type="VAN_BAN_DEN" />
      <Association Name="LOAI_VAN_BAN_VAN_BAN_DI" Member="VAN_BAN_DIs" ThisKey="ID_LOAI_VAN_BAN" OtherKey="ID_LOAI_VAN_BAN" Type="VAN_BAN_DI" />
    </Type>
  </Table>
  <Table Name="dbo.MENUFORM" Member="MENUFORMs">
    <Type Name="MENUFORM">
      <Column Name="MENUFORMID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MENUFORMNAME" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MENUFORMURL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SORTPARENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SORT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MENUFORMPARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MENUFORM_GROUPMENUFUNC" Member="GROUPMENUFUNCs" ThisKey="MENUFORMID" OtherKey="MENUFORMID" Type="GROUPMENUFUNC" />
    </Type>
  </Table>
  <Table Name="dbo.NOI_BAN_HANH" Member="NOI_BAN_HANHs">
    <Type Name="NOI_BAN_HANH">
      <Column Name="ID_NOI_BAN_HANH" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOI_BAN_HANH" Member="NOI_BAN_HANH1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MO_TA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="NOI_BAN_HANH_THIET_LAP_THONG_TIN" Member="THIET_LAP_THONG_TINs" ThisKey="ID_NOI_BAN_HANH" OtherKey="ID_NOI_BAN_HANH" Type="THIET_LAP_THONG_TIN" />
      <Association Name="NOI_BAN_HANH_VAN_BAN_DEN" Member="VAN_BAN_DENs" ThisKey="ID_NOI_BAN_HANH" OtherKey="ID_DON_VI_DEN" Type="VAN_BAN_DEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG_BAN" Member="PHONG_BANs">
    <Type Name="PHONG_BAN">
      <Column Name="ID_PHONG_BAN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_PHONG_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="PHONG_BAN_VAN_BAN_NOI_BO" Member="VAN_BAN_NOI_BOs" ThisKey="ID_PHONG_BAN" OtherKey="ID_PHONG_BAN_NHAN" Type="VAN_BAN_NOI_BO" />
      <Association Name="PHONG_BAN_VAN_BAN_NOI_BO1" Member="VAN_BAN_NOI_BOs1" ThisKey="ID_PHONG_BAN" OtherKey="ID_PHONG_BAN_BAN_HANH" Type="VAN_BAN_NOI_BO" />
    </Type>
  </Table>
  <Table Name="dbo.SALE_NHAN_VIEN" Member="SALE_NHAN_VIENs">
    <Type Name="SALE_NHAN_VIEN">
      <Column Name="ID_NHAN_VIEN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_NHAN_VIEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HO_TEN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NGHI_VIEC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MAT_KHAU" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IS_ADMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_CONG_TY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SALE_NHAN_VIEN_GROUPMENUFUNC" Member="GROUPMENUFUNCs" ThisKey="ID_NHAN_VIEN" OtherKey="ID_NHAN_VIEN" Type="GROUPMENUFUNC" />
      <Association Name="THONG_TIN_CONG_TY_SALE_NHAN_VIEN" Member="THONG_TIN_CONG_TY" ThisKey="ID_CONG_TY" OtherKey="ID_CONG_TY" Type="THONG_TIN_CONG_TY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SO_VAN_BAN" Member="SO_VAN_BANs">
    <Type Name="SO_VAN_BAN">
      <Column Name="ID_SO_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_SO_VAN_BAN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LOAI_SO_DI_DEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SO_VAN_BAN_VAN_BAN_DEN" Member="VAN_BAN_DENs" ThisKey="ID_SO_VAN_BAN" OtherKey="ID_SO_VAN_BAN" Type="VAN_BAN_DEN" />
      <Association Name="SO_VAN_BAN_VAN_BAN_DI" Member="VAN_BAN_DIs" ThisKey="ID_SO_VAN_BAN" OtherKey="ID_SO_VAN_BAN" Type="VAN_BAN_DI" />
    </Type>
  </Table>
  <Table Name="dbo.THIET_LAP_THONG_TIN" Member="THIET_LAP_THONG_TINs">
    <Type Name="THIET_LAP_THONG_TIN">
      <Column Name="ID_THIET_LAP_THONG_TIN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGUOI_KY_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_GUI_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_DUYET_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_NHAN_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ID_NOI_BAN_HANH" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="NOI_BAN_HANH_THIET_LAP_THONG_TIN" Member="NOI_BAN_HANH" ThisKey="ID_NOI_BAN_HANH" OtherKey="ID_NOI_BAN_HANH" Type="NOI_BAN_HANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONG_TIN_CONG_TY" Member="THONG_TIN_CONG_Ties">
    <Type Name="THONG_TIN_CONG_TY">
      <Column Name="ID_CONG_TY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_CONG_TY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIA_CHI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIEN_THOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WEBSITE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MA_SO_THUE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LO_GO" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LINH_VUC" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MO_TA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TRANG_THAI_KICH_HOAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ICON" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="THONG_TIN_CONG_TY_SALE_NHAN_VIEN" Member="SALE_NHAN_VIENs" ThisKey="ID_CONG_TY" OtherKey="ID_CONG_TY" Type="SALE_NHAN_VIEN" />
    </Type>
  </Table>
  <Table Name="dbo.VAN_BAN_DEN" Member="VAN_BAN_DENs">
    <Type Name="VAN_BAN_DEN">
      <Column Name="ID_VAN_BAN_DEN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SO_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ID_LOAI_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SO_KY_HIEU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SO_DEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAY_BAN_HANH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAY_DEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_DON_VI_DEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TRICH_YEU" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOI_NHAN_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_KY_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_DUYET_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SO_TRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="VAN_BAN_DEN_FILE_NAME" Member="FILE_NAMEs" ThisKey="ID_VAN_BAN_DEN" OtherKey="ID_VAN_BAN_DEN" Type="FILE_NAME" />
      <Association Name="LOAI_VAN_BAN_VAN_BAN_DEN" Member="LOAI_VAN_BAN" ThisKey="ID_LOAI_VAN_BAN" OtherKey="ID_LOAI_VAN_BAN" Type="LOAI_VAN_BAN" IsForeignKey="true" />
      <Association Name="NOI_BAN_HANH_VAN_BAN_DEN" Member="NOI_BAN_HANH" ThisKey="ID_DON_VI_DEN" OtherKey="ID_NOI_BAN_HANH" Type="NOI_BAN_HANH" IsForeignKey="true" />
      <Association Name="SO_VAN_BAN_VAN_BAN_DEN" Member="SO_VAN_BAN" ThisKey="ID_SO_VAN_BAN" OtherKey="ID_SO_VAN_BAN" Type="SO_VAN_BAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VAN_BAN_DI" Member="VAN_BAN_DIs">
    <Type Name="VAN_BAN_DI">
      <Column Name="ID_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SO_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ID_LOAI_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SO_KY_HIEU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SO_DI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAY_BAN_HANH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TRICH_YEU" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="NOI_NHAN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOI_GUI_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_KY_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_DUYET_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SO_TRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SO_LUONG_BAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VAN_BAN_DI_FILE_NAME" Member="FILE_NAMEs" ThisKey="ID_VAN_BAN" OtherKey="ID_VAN_BAN_DI" Type="FILE_NAME" />
      <Association Name="LOAI_VAN_BAN_VAN_BAN_DI" Member="LOAI_VAN_BAN" ThisKey="ID_LOAI_VAN_BAN" OtherKey="ID_LOAI_VAN_BAN" Type="LOAI_VAN_BAN" IsForeignKey="true" />
      <Association Name="SO_VAN_BAN_VAN_BAN_DI" Member="SO_VAN_BAN" ThisKey="ID_SO_VAN_BAN" OtherKey="ID_SO_VAN_BAN" Type="SO_VAN_BAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VAN_BAN_NOI_BO" Member="VAN_BAN_NOI_BOs">
    <Type Name="VAN_BAN_NOI_BO">
      <Column Name="ID_VAN_BAN_NOI_BO" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SO_KY_HIEU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEN_VAN_BAN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ID_LOAI_VAN_BAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAY_BAN_HANH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="TRICH_YEU" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="NGUOI_NHAN_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_KY_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGUOI_DUYET_VAN_BAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ID_PHONG_BAN_NHAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ID_PHONG_BAN_BAN_HANH" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VAN_BAN_NOI_BO_FILE_NAME" Member="FILE_NAMEs" ThisKey="ID_VAN_BAN_NOI_BO" OtherKey="ID_VAN_BAN_NOI_BO" Type="FILE_NAME" />
      <Association Name="PHONG_BAN_VAN_BAN_NOI_BO" Member="PHONG_BAN" ThisKey="ID_PHONG_BAN_NHAN" OtherKey="ID_PHONG_BAN" Type="PHONG_BAN" IsForeignKey="true" />
      <Association Name="PHONG_BAN_VAN_BAN_NOI_BO1" Member="PHONG_BAN1" ThisKey="ID_PHONG_BAN_BAN_HANH" OtherKey="ID_PHONG_BAN" Type="PHONG_BAN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>